<!DOCTYPE html>
<html>
<head>
    <title>Sales Report - {{ $date }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; }
        .stats-box { background: #f8f9fa; padding: 15px; margin-bottom: 20px; border: 1px solid #ddd; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #007bff; color: white; }
        .footer { margin-top: 30px; font-size: 10px; color: #777; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>AutoSparePart Sales Report</h1>
        <p>Period: Last {{ $days }} Days | Generated on: {{ $date }}</p>
    </div>

    <div class="stats-box">
        <strong>Total Revenue:</strong> ${{ number_format($totalRevenue, 2) }} <br>
        <strong>Report generated by:</strong> Admin Panel
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Orders</th>
                <th>Revenue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($salesData as $data)
            <tr>
                <td>{{ $data->date }}</td>
                <td>{{ $data->order_count }}</td>
                <td>${{ number_format($data->total_revenue, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        &copy; {{ date('Y') }} autosparepart.com - Internal Use Only
    </div>
</body>
</html>