<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        /* PDF specific styling */
        body { font-family: 'Helvetica', sans-serif; color: #333; font-size: 11px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #444; padding-bottom: 10px; }
        .report-title { font-size: 18px; font-weight: bold; text-transform: uppercase; margin-bottom: 5px; }
        .report-meta { color: #666; font-size: 10px; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #f2f2f2; color: #000; font-weight: bold; text-align: left; border: 1px solid #ccc; padding: 8px; }
        td { border: 1px solid #ccc; padding: 6px; vertical-align: top; }
        
        /* Excel logic: This class helps Maatwebsite auto-format numbers if needed */
        .text-right { text-align: right; }
        .stock-low { color: #e53e3e; font-weight: bold; }
        .footer { margin-top: 20px; font-size: 9px; color: #999; text-align: center; }
    </style>
</head>
<body>

    <div class="header">
        <div class="report-title">Spare Parts Inventory Report</div>
        <div class="report-meta">
            Generated on: {{ now()->format('d M Y, H:i A') }} | 
            Total Items: {{ $parts->count() }} | 
            Total Valuation: {{ number_format($parts->sum(fn($p) => $p->price * $p->stock_quantity)) }} RWF
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th width="20%">Part Name</th>
                <th width="15%">SKU / PN</th>
                <th width="12%">Category</th>
                <th width="10%">Brand</th>
                <th width="12%">Price (RWF)</th>
                <th width="8%">Stock</th>
                <th width="23%">Vehicle Compatibility</th>
            </tr>
        </thead>
        <tbody>
            @foreach($parts as $part)
            <tr>
                <td>
                    <strong>{{ $part->part_name }}</strong><br>
                    <small style="color: #777;">OEM: {{ $part->oem_number ?? 'N/A' }}</small>
                </td>
                <td>{{ $part->sku }}</td>
                <td>{{ $part->category->category_name ?? 'N/A' }}</td>
                <td>{{ $part->partBrand->name ?? 'N/A' }}</td>
                <td class="text-right">{{ number_format($part->price) }}</td>
                <td class="text-right {{ $part->stock_quantity <= 5 ? 'stock-low' : '' }}">
                    {{ $part->stock_quantity }}
                </td>
                <td>
                    @if($part->fitments->count() > 0)
                        @foreach($part->fitments as $f)
                            {{ $f->specification->vehicleModel->name ?? '' }} ({{ $f->start_year }}){{ !$loop->last ? ', ' : '' }}
                        @endforeach
                    @else
                        <span style="color: #999;">Universal Fit</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        End of Report - Generated by Laravel Inventory System
    </div>

</body>
</html>