<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; font-size: 10px; } /* Slightly smaller for more data */
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #444; padding-bottom: 10px; }
        .report-title { font-size: 16px; font-weight: bold; text-transform: uppercase; margin-bottom: 5px; }
        .report-meta { color: #666; font-size: 9px; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 10px; table-layout: fixed; }
        th { background-color: #f2f2f2; color: #000; font-weight: bold; text-align: left; border: 1px solid #ccc; padding: 6px; }
        td { border: 1px solid #ccc; padding: 6px; vertical-align: top; word-wrap: break-word; }
        
        .text-right { text-align: right; }
        .stock-low { color: #e53e3e; font-weight: bold; }
        .substitute-label { font-size: 8px; color: #4c51bf; font-weight: bold; text-transform: uppercase; margin-top: 4px; display: block; }
        .substitute-item { font-size: 9px; color: #555; background: #f0f4ff; padding: 1px 3px; border-radius: 2px; }
        .footer { margin-top: 20px; font-size: 8px; color: #999; text-align: center; }
    </style>
</head>
<body>

    <div class="header">
        <div class="report-title">Spare Parts Inventory Report</div>
        <div class="report-meta">
            Generated on: {{ now()->format('d M Y, H:i A') }} | 
            Total Items: {{ $parts->count() }} | 
            Total Valuation: {{ number_format($parts->sum(fn($p) => $p->price * $p->stock_quantity)) }} RWF
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th width="18%">Part Name</th>
                <th width="17%">SKU / Substitutes</th>
                <th width="12%">Category</th>
                <th width="10%">Brand</th>
                <th width="12%">Price (RWF)</th>
                <th width="7%">Stock</th>
                <th width="24%">Vehicle Compatibility</th>
            </tr>
        </thead>
        <tbody>
            @foreach($parts as $part)
            <tr>
                <td>
                    <strong>{{ $part->part_name }}</strong><br>
                    <small style="color: #777;">OEM: {{ $part->oem_number ?? 'N/A' }}</small>
                </td>
                <td>
                    <div>{{ $part->sku }}</div>
                    @if($part->substitutions && $part->substitutions->count() > 0)
                        <span class="substitute-label">Substitutes:</span>
                        @foreach($part->substitutions as $sub)
                            <span class="substitute-item">{{ $sub->sku }}</span>{{ !$loop->last ? ',' : '' }}
                        @endforeach
                    @endif
                </td>
                <td>{{ $part->category->category_name ?? 'N/A' }}</td>
                <td>{{ $part->partBrand->name ?? 'N/A' }}</td>
                <td class="text-right">{{ number_format($part->price) }}</td>
                <td class="text-right {{ $part->stock_quantity <= 5 ? 'stock-low' : '' }}">
                    {{ $part->stock_quantity }}
                </td>
                <td>
                    @if($part->fitments && $part->fitments->count() > 0)
                        @foreach($part->fitments as $f)
                            {{ $f->specification->variant->name ?? 'N/A' }}{{ !$loop->last ? ', ' : '' }}
                        @endforeach
                    @else
                        <span style="color: #999;">Universal Fit</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        End of Report - Generated by Laravel Inventory System
    </div>

</body>
</html>